language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - tox --version
script: tox
notifications:
  email: false